[package]
name = "webassembly"
version = "0.1.0"
edition = "2021"
authors = ["Robiel Tesfazghi <robboytm@gmail.com>"] 
description = "A simple webassembly project"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
